### PR TITLE
Range fix?

### LINKED ISSUE #773: Upgrading to version 0.19.10 breaks compilation
Hello,
We are using Lalrpop with version 0.19.9 and regex version 1.7.3
When we upgraded lalrpop to version 0.19.10 we are getting:
```
error: failed to run custom build command for `cel-parser v0.1.3-alpha.0 (/Users/omer/workspace/cel-rust/parser)`

Caused by:
  process didn't exit successfully: `/Users/omer/workspace/cel-rust/target/debug/build/cel-parser-062774afdad45860/build-script-build` (exit status: 101)
  --- stdout
  processing file `/Users/omer/workspace/cel-rust/parser/src/cel.lalrpop`

  --- stderr
  thread 'main' panicked at 'attempt to subtract with overflow', /Users/omer/.cargo/registry/src/github.com-1ecc6299db9ec823/lalrpop-0.19.10/src/lexer/dfa/overlap.rs:73:49
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

Any ideas what can cause that?

### PR DESCRIPTION
**Pull request by Pat-Lafon**
Working to fix #773. The null case is a little hard, so I think that needs special handling?

One issue I had is with the repeat test as with the new logic, I end up creating a single character range of just 'l'. I added a sort to make things nicer but it might be unnecessary. So this fix might add additional ranges

### CODE REVIEW

**Comment by Pat-Lafon** [comment]
@dburgener Can you check this over?

**Comment by dburgener** [comment]
This seems reasonable to me.  The key observation here I think is that mid_range really needs to be exactly the overlapping range.  So putting the adjustment on low and high preserves that and makes sense.

**Comment by youknowone** [comment]
A question. In conclusion is this actually better than exclusive ranges?
To decide between reverting inclusive ranges or appending this patch.

**Comment by Pat-Lafon** [comment]
My understanding is that the intent of `Test` was to be an inclusive range given the comments  https://github.com/lalrpop/lalrpop/blob/3b203c676cee618d20945d66ec65069372a942dd/lalrpop/src/lexer/nfa/mod.rs#L31 and examples https://github.com/lalrpop/lalrpop/blob/3b203c676cee618d20945d66ec65069372a942dd/lalrpop/src/lexer/dfa/overlap.rs#L5-L14.

However, this part of the code was introduced before `RangeInclusive` was added to the standard library(some of the commits are 7 years old) so this functionality had to be implemented manually alongside the original `Range` which is exclusive at one end.

The original motivation for the change was in clippy pointing out that because of this, some of the test cases like `0..9` are not actually covering the range of characters that one might expect(which would be `0..=9`).

In porting over to `RangeInclusive`, there are some nice benefits of having the type more strongly enforce/describe the invariant, maybe clarifying parts of the code that broke this invariant, reusing already existing standard library code instead of maintaining lalrpop's own version, and in having test cases over the full range of characters that is expected.

However, there are obvious drawbacks in doing this as we've seen, largely along the lines of "if it's not broken don't fix it", in that introducing off-by-one errors are easy to do, and that the tests we had were not sufficient to cover against breaking changes.

File: lalrpop/src/lexer/dfa/overlap.rs [hunk 1]
```diff
@@ -69,10 +75,18 @@ fn add_range(range: Test, start_index: usize, disjoint_ranges: &mut Vec<Test>) {
...
+            // So we adjust the end of the low_range and start of max_range as these elements are already included in the start of their corresponding next ranges.
+
+            let low_range = if mid_min == 0 {
+                // This is an edgecase where both ranges start at the null character
+                // In this case we don't want to create a range from 0 to -1
+                // Thus we create an empty range
+                Test::new(RangeInclusive::new(1, 0))
+            } else {
+                Test::new(min_min..=mid_min - 1)
+            };
```
Comment (youknowone) [inline lalrpop/src/lexer/dfa/overlap.rs:87]:
```suggestion
            // This is an edgecase where both ranges start at the null character
            // In this case we don't want to create a range from 0 to -1
            // Thus we create an empty range
            Test::new(min_min..=mid_min.checked_sub(1))
```
Is this possible? I don't know well about this code. So please check which version express the design intent better.

**Review by youknowone — COMMENTED** [review]
The motivation sounds reasonable. Thank you for explanation!

File: lalrpop/src/lexer/dfa/overlap.rs (hunk 1 above)
Comment (Pat-Lafon) [reply lalrpop/src/lexer/dfa/overlap.rs:87]: `checked_sub` returns an option right? So you need to handle the `None` case. I guess one could write something like 

```rust
Test::new(mid_min.checked_sub(1).map_or_else(||RangeInclusive::new(1, 0), |v| min_min..=v))
```

I'm not sure if that's cleaner?

Comment (youknowone) [reply lalrpop/src/lexer/dfa/overlap.rs:87]: oh, i am sorry. I was thinking of `saturated_sub` 😂

Comment (youknowone) [reply lalrpop/src/lexer/dfa/overlap.rs:87]: https://doc.rust-lang.org/std/primitive.u32.html#method.saturating_sub

Comment (Pat-Lafon) [reply lalrpop/src/lexer/dfa/overlap.rs:87]: Currently, if mid_min would underflow, I am returning an empty range which will get ignored later. With saturating_sub, we would end up with a valid range of `\0`..=`\0`. I think this would mean having a duplicate value, probably `\0`..=`\0` twice.

**Comment by eeeebbbbrrrr** [comment]
Hi, this doesn't seem to fix the problem.  It fixes the overflow error during parser generation, but now the generated parser has a number of compilation problems:

```
error[E0432]: unresolved import `self::__lalrpop_util::lexer`
  --> src/zql/parser.rs:30:31
   |
30 |     use self::__lalrpop_util::lexer::Token;
   |                               ^^^^^ could not find `lexer` in `__lalrpop_util`

error[E0432]: unresolved import `self::__lalrpop_util::lexer`
    --> src/zql/parser.rs:7221:31
     |
7221 |     use self::__lalrpop_util::lexer::Token;
     |                               ^^^^^ could not find `lexer` in `__lalrpop_util`

error[E0432]: unresolved import `self::__lalrpop_util::lexer`
     --> src/zql/parser.rs:13565:31
      |
13565 |     use self::__lalrpop_util::lexer::Token;
      |                               ^^^^^ could not find `lexer` in `__lalrpop_util`

error[E0432]: unresolved imports `self::__lalrpop_util::lexer`, `crate::zql::parser::Token`
     --> src/zql/ast.rs:13:5
      |
13    | use crate::zql::parser::Token;
      |     ^^^^^^^^^^^^^^^^^^^^^^^^^
      |
     ::: src/zql/parser.rs:19968:38
      |
19968 | pub(crate) use self::__lalrpop_util::lexer::Token;
      |                                      ^^^^^ could not find `lexer` in `__lalrpop_util`

error[E0433]: failed to resolve: could not find `lexer` in `__lalrpop_util`
    --> src/zql/parser.rs:2351:34
     |
2351 |         builder: __lalrpop_util::lexer::MatcherBuilder,
     |                                  ^^^^^ could not find `lexer` in `__lalrpop_util`

error[E0433]: failed to resolve: could not find `lexer` in `__lalrpop_util`
    --> src/zql/parser.rs:8695:34
     |
8695 |         builder: __lalrpop_util::lexer::MatcherBuilder,
     |                                  ^^^^^ could not find `lexer` in `__lalrpop_util`

error[E0433]: failed to resolve: could not find `lexer` in `__lalrpop_util`
     --> src/zql/parser.rs:15046:34
      |
15046 |         builder: __lalrpop_util::lexer::MatcherBuilder,
      |                                  ^^^^^ could not find `lexer` in `__lalrpop_util`

error[E0433]: failed to resolve: could not find `lexer` in `__lalrpop_util`
     --> src/zql/parser.rs:19914:45
      |
19914 |     pub fn new_builder() -> __lalrpop_util::lexer::MatcherBuilder {
      |                                             ^^^^^ could not find `lexer` in `__lalrpop_util`

error[E0433]: failed to resolve: could not find `lexer` in `__lalrpop_util`
     --> src/zql/parser.rs:19965:25
      |
19965 |         __lalrpop_util::lexer::MatcherBuilder::new(__strs.iter().copied()).unwrap()
      |                         ^^^^^ could not find `lexer` in `__lalrpop_util`
```

I'm no lalrpop expert, and I doubt our parser would be easy to pull out as a standalone test, but this is the grammar in question:  https://github.com/zombodb/zombodb/blob/master/src/zql/parser.lalrpop

I'm happy to try and help however I can.

**Comment by dburgener** [comment]
I think this may be a consequence of how you're doing the git build.

I took a separate repo I maintain that depends on lalrpop (which works fine with 0.19.10), and I pinned it to the 0.19.10 tag in git, and was able to reproduce similar errors to what you posted.

I think added:

```
lalrpop-util = { git = "https://github.com/lalrpop/lalrpop.git", tag = "0.19.10"}
```

(I didn't previously have any specific lalrpop-util dependency to remove).

And that made the problem go away resulting in a clean compile.  I'm not sure what's really going on, but somehow the git build seems to be preventing lalrpop-util from getting pulled in appropriately.

Can you try adding the lalrpop-util git dependency and see if that addresses it on your end as well?

If so, I think this isn't a problem with the 0.19.10 release or the fix in this issue, but something about the dependency tracking in doing manual git tracks in Cargo.toml, and presumably a yank of 0.19.10 and publish of 0.19.11 with this fix should resolve your problem and not hit the above error.
