### ISSUE TITLE
Error in 0.20's generated code

### ISSUE THREAD

**Issue by nwalfield** [lalrpop/lalrpop#801]
I'm trying to upgrade sequoia-openpgp's dependency on lalrpop from 0.19 to 0.20.  Unfortunately, I'm encountering an error in the generated code (I think):

```
$ git clone https://gitlab.com/sequoia-pgp/sequoia.git
Cloning into 'sequoia'...
...
$ emacs Cargo.toml
$ git diff Cargo.toml
diff --git a/openpgp/Cargo.toml b/openpgp/Cargo.toml
index 8a4ce2fa..d7724731 100644
--- a/openpgp/Cargo.toml
+++ b/openpgp/Cargo.toml
@@ -110,7 +110,7 @@ getrandom = { version = "0.2", features = ["js"] }
 rand07 = { package = "rand", version = "0.7", features = ["wasm-bindgen"] }
 
 [build-dependencies]
-lalrpop = { version = ">=0.17, <0.20", default-features = false }
+lalrpop = { version = "0.20", default-features = false }
 
 [dev-dependencies]
 quickcheck = { version = "1", default-features = false }

$ cargo test
...
error[E0407]: method `expected_tokens_from_states` is not a member of trait `__state_machine::ParserDefinition`
   --> /tmp/sequoia/target/debug/build/sequoia-openpgp-4070d8d6c8494d5c/out/cert/parser/low_level/grammar.rs:303:9
    |
303 | /         fn expected_tokens_from_states(&self, states: &[i8]) -> alloc::vec::Vec<alloc::string::String> {
304 | |             __expected_tokens_from_states(states, core::marker::PhantomData::<()>)
305 | |         }
    | |_________^ not a member of trait `__state_machine::ParserDefinition`

error[E0407]: method `expected_tokens_from_states` is not a member of trait `__state_machine::ParserDefinition`
   --> /tmp/sequoia/target/debug/build/sequoia-openpgp-4070d8d6c8494d5c/out/message/grammar.rs:294:9
    |
294 | /         fn expected_tokens_from_states(&self, states: &[i8]) -> alloc::vec::Vec<alloc::string::String> {
295 | |             __expected_tokens_from_states(states, core::marker::PhantomData::<()>)
296 | |         }
    | |_________^ not a member of trait `__state_machine::ParserDefinition`

error[E0407]: method `expected_tokens_from_states` is not a member of trait `__state_machine::ParserDefinition`
   --> /tmp/sequoia/target/debug/build/sequoia-openpgp-4070d8d6c8494d5c/out/regex/grammar.rs:524:9
    |
524 | /         fn expected_tokens_from_states(&self, states: &[i8]) -> alloc::vec::Vec<alloc::string::String> {
525 | |             __expected_tokens_from_states(states, core::marker::PhantomData::<(&())>)
526 | |         }
    | |_________^ not a member of trait `__state_machine::ParserDefinition`

For more information about this error, try `rustc --explain E0407`.
error: could not compile `sequoia-openpgp` due to 3 previous errors
warning: build failed, waiting for other jobs to finish...
error: could not compile `sequoia-openpgp` due to 3 previous errors
$ rustc --version
rustc 1.64.0 (a55dd71d5 2022-09-19)
```

We haven't changed the lalrpop code in a long time, and it compiles fine with 0.19.

**Comment by youknowone** [comment]
Did you also change `lalrpop-util`?

**Comment by nwalfield** [comment]
> Did you also change `lalrpop-util`?

Oh no!  That was indeed the problem :/.  Thanks for your help, and I apologize for the noise.
